server.port=8087

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=class403

spring.devtools.livereload.enabled=true
